20240920_vcsa_config

diff --git a/templates/vcsa.sh.template b/templates/vcsa.sh.template
--- a/templates/vcsa.sh.template
+++ b/templates/vcsa.sh.template
@@ -1,6 +1,7 @@
 #!/bin/bash
 #
-source /home/ubuntu/download_file.sh
+source /home/ubuntu/bash/download_file.sh
+source /home/ubuntu/vcenter/vcenter_api.sh
 jsonFile="${jsonFile}"
 SLACK_WEBHOOK_URL_LOCAL=${SLACK_WEBHOOK_URL}
 log_file="/tmp/vcsa.log"
@@ -23,11 +24,15 @@ rm -fr /tmp/vcenter_cdrom
 mkdir -p /tmp/vcenter_cdrom
 cp -r /tmp/vcenter_cdrom_mount/* /tmp/vcenter_cdrom
 rm -fr /tmp/vcenter_cdrom_mount
-contents="$(jq '.new_vcsa.esxi.hostname = "esxi01.'${domain}'" |
+ssoDomain=$(jq -r '.spec.vsphere.ssoDomain' $jsonFile)
+vsphere_nested_username="administrator"
+vsphere_nested_password="${GENERIC_PASSWORD}"
+api_host="${vcsa_name}.${domain}"
+contents="$(jq '.new_vcsa.esxi.hostname = "${esxi_basename}1.'${domain}'" |
                 .new_vcsa.esxi.username = "root" |
                 .new_vcsa.esxi.password = "${GENERIC_PASSWORD}" |
-                .new_vcsa.esxi.VCSA_cluster.datacenter = "dc1" |
-                .new_vcsa.esxi.VCSA_cluster.cluster = "cluster1" |
+                .new_vcsa.esxi.VCSA_cluster.datacenter = "'${dc}'" |
+                .new_vcsa.esxi.VCSA_cluster.cluster = "'${cluster_basename}'1" |
                 .new_vcsa.esxi.VCSA_cluster.disks_for_vsan.cache_disk[0] = "mpx.vmhba0:C0:T1:L0" |
                 .new_vcsa.esxi.VCSA_cluster.disks_for_vsan.capacity_disk[0] = "mpx.vmhba0:C0:T2:L0" |
                 .new_vcsa.esxi.VCSA_cluster.enable_vsan_esa = false |
@@ -44,8 +49,80 @@ contents="$(jq '.new_vcsa.esxi.hostname = "esxi01.'${domain}'" |
                 .new_vcsa.os.ntp_servers = "'${ip_gw}'" |
                 .new_vcsa.os.ssh_enable = true |
                 .new_vcsa.sso.password = "${GENERIC_PASSWORD}" |
-                .new_vcsa.sso.domain_name = "'$(jq -r .spec.vsphere.ssoDomain $jsonFile)'" |
+                .new_vcsa.sso.domain_name = "'${ssoDomain}'" |
                 .ceip.settings.ceip_enabled = 'false'' /home/ubuntu/vCSA_with_cluster_on_ESXi.json)"
 echo "${contents}" | jq 'del (.new_vcsa.esxi.VCSA_cluster.storage_pool.single_tier)' | tee /home/ubuntu/vcenter_config.json
 /tmp/vcenter_cdrom/vcsa-cli-installer/lin64/vcsa-deploy install --accept-eula --acknowledge-ceip --no-esx-ssl-verify /home/ubuntu/vcenter_config.json | tee -a ${log_file}
 if [ -z "${SLACK_WEBHOOK_URL_LOCAL}" ] ; then echo "ignoring slack update" ; else curl -X POST -H 'Content-type: application/json' --data '{"text":"'$(date "+%Y-%m-%d,%H:%M:%S")', '${deployment_name}': VCSA installed"}' ${SLACK_WEBHOOK_URL_LOCAL} >/dev/null 2>&1; fi
+ssh-keygen -f /home/ubuntu/.ssh/known_hosts -R ${vcsa_name}.${domain} || true
+count=1
+until $(curl --output /dev/null --silent --head -k https://${vcsa_name}.${domain})
+do
+  echo "Attempt ${count}: Waiting for vCenter host https://${vcsa_name}.${domain} to be reachable..." | tee -a ${log_file}
+  sleep 10
+  count=$((count+1))
+    if [[ "${count}" -eq 60 ]]; then
+      echo "ERROR: Unable to connect to vCenter host https://${vcsa_name}.${domain}" | tee -a ${log_file}
+      if [ -z "${SLACK_WEBHOOK_URL_LOCAL}" ] ; then echo "ignoring slack update" ; else curl -X POST -H 'Content-type: application/json' --data '{"text":"'$(date "+%Y-%m-%d,%H:%M:%S")', ${deployment_name}: vCenter host https://${vcsa_name}.${domain} unable to reach"}' ${SLACK_WEBHOOK_URL_LOCAL} >/dev/null 2>&1; fi
+      exit
+    fi
+done
+if [ -z "${SLACK_WEBHOOK_URL_LOCAL}" ] ; then echo "ignoring slack update" ; else curl -X POST -H 'Content-type: application/json' --data '{"text":"'$(date "+%Y-%m-%d,%H:%M:%S")', ${deployment_name}: vCenter host https://${vcsa_name}.${domain} reachable"}' ${SLACK_WEBHOOK_URL_LOCAL} >/dev/null 2>&1; fi
+echo "vCenter host https://${vcsa_name}.${domain} reachable" | tee -a ${log_file}
+token=$(/bin/bash /home/ubuntu/vcenter/create_vcenter_api_session.sh "${vsphere_nested_username}" "${ssoDomain}" "${vsphere_nested_password}" "${api_host}")
+vcenter_api 6 10 "PUT" $token '{"enabled":true}' "${api_host}" "api/appliance/access/ssh"
+vcenter_api 6 10 "PUT" $token '{"enabled":true}' "${api_host}" "api/appliance/access/dcui"
+vcenter_api 6 10 "PUT" $token '{"enabled":true}' "${api_host}" "api/appliance/access/consolecli"
+vcenter_api 6 10 "PUT" $token '{"enabled":true,"timeout":120}' "${api_host}" "api/appliance/access/shell"
+vcenter_api 6 10 "PUT" $token '{"max_days":0,"min_days":0,"warn_days":0}' "${api_host}" "api/appliance/local-accounts/global-policy"
+#
+# Add cluster(s) in dc
+#
+count_cluster=$(($(jq -r '.spec.esxi.ips | length' $jsonFile)/3))
+for cluster in $(seq 1 ${count_cluster})
+do
+  if [[ ${cluster} -ne 1 ]] ; then
+    load_govc_env_wo_cluster
+    echo "Adding vSphere cluster "${cluster_basename}${cluster}" | tee -a ${log_file}
+    govc cluster.create "${cluster_basename}${cluster}" > /dev/null
+  fi
+done
+#
+# Add host in the cluster(s)
+#
+for esxi in $(seq 1 $(jq -r '.spec.esxi.ips | length' $jsonFile))
+do
+  if [[ ${esxi} != 1 ]] ; then
+    load_govc_env_with_cluster "${basename_cluster}$((($esxi-1)/3+1))"
+    echo "Adding ESXi host ${esxi_basename}${esxi}.${domain} in cluster ${basename_cluster}$((($esxi-1)/3+1))" | tee -a ${log_file}
+    govc cluster.add -hostname "${esxi_basename}${esxi}.${domain}" -username "root" -password "${GENERIC_PASSWORD}" -noverify > /dev/null
+  fi
+done
+#
+# Network config
+#
+load_govc_env_wo_cluster
+echo "create vds called vds1-mgmt" | tee -a ${log_file}
+govc dvs.create -mtu 1500 -discovery-protocol lldp -product-version=7.0.2 vds1-mgmt > /dev/null
+echo "create vds called vds2-VMotion" | tee -a ${log_file}
+govc dvs.create -mtu 1500 -discovery-protocol lldp -product-version=7.0.2 vds2-VMotion > /dev/null
+echo "create vds called vds3-VSAN" | tee -a ${log_file}
+govc dvs.create -mtu 1500 -discovery-protocol lldp -product-version=7.0.2 vds3-VSAN > /dev/null
+echo "create portgroup mgmt in vds vds1-mgmt" | tee -a ${log_file}
+govc dvs.portgroup.add -dvs vds1-mgmt -vlan "$(jq -c -r --arg arg "MANAGEMENT" '.spec.networks[] | select( .type == $arg).vlan_id' $jsonFile)" mgmt > /dev/null
+echo "create portgroup mgmt-vmk in vds vds1-mgmt" | tee -a ${log_file}
+govc dvs.portgroup.add -dvs vds1-mgmt -vlan "$(jq -c -r --arg arg "MANAGEMENT" '.spec.networks[] | select( .type == $arg).vlan_id' $jsonFile)" mgmt-vmk > /dev/null
+echo "create portgroup VSAN in vds vds3-VSAN" | tee -a ${log_file}
+govc dvs.portgroup.add -dvs vds3-VSAN -vlan "$(jq -c -r --arg arg "VSAN" '.spec.networks[] | select( .type == $arg).vlan_id' $jsonFile)" VSAN > /dev/null
+echo "create portgroup VMOTION in vds vds2-VMotion" | tee -a ${log_file}
+govc dvs.portgroup.add -dvs vds2-VMotion -vlan "$(jq -c -r --arg arg "VMOTION" '.spec.networks[] | select( .type == $arg).vlan_id' $jsonFile)" VMOTION > /dev/null
+#
+for esxi in $(seq 1 $(jq -r '.spec.esxi.ips | length' $jsonFile))
+do
+  echo "Adding ESXi host ${esxi_basename}${esxi}.${domain} on port-group vds1-mgmt on pnic vmnic1" | tee -a ${log_file}
+  govc dvs.add -dvs vds1-mgmt -pnic=vmnic1 "${esxi_basename}${esxi}.${domain}"
+  echo "Adding ESXi host ${esxi_basename}${esxi}.${domain} on port-group vds2-VMotion on pnic vmnic1" | tee -a ${log_file}
+  govc dvs.add -dvs vds2-VMotion -pnic=vmnic1 "${esxi_basename}${esxi}.${domain}"
+  echo "Adding ESXi host ${esxi_basename}${esxi}.${domain} on port-group vds3-VSAN on pnic vmnic1" | tee -a ${log_file}
+  govc dvs.add -dvs vds3-VSAN -pnic=vmnic1 "${esxi_basename}${esxi}.${domain}"
+done
